import { stat } from 'fs';

const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  userId: state => state.user.userID,
  introduction: state => state.user.introduction,
  status: state => state.user.status,
  roles: state => state.user.roles,
  setting: state => state.user.setting,
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters,
  errorLogs: state => state.errorLog.logs,
  routerList: state => state.routerlist,
  goodsInfo: state => state.goodsInfo.goodsInfo,
  selectedOrderGoods: state => state.orderGoods.selectedOrderGoods,
  category: state => state.goodsInfo.category,
  attribute: state => state.goodsInfo.attribute,
  skus: state => state.goodsInfo.skus,
  skuDetail: state => state.goodsInfo.skuDetail,
  detailForm: state => state.goodsInfo.detailForm,
  origin: state => state.goodsInfo.origin,
  orderObj: state => state.order.orderObj,
  businessType: state => state.goodsInfo.businessType,
  checkedPurchaseGood: state => state.purchase.checkedPurchaseGood,
  deleteList: state => state.purchase.deleteList
};
export default getters;
